import openmc

# Open the statepoint file generated by the simulation
with openmc.StatePoint('statepoint.100.h5') as sp:
    # Retrieve the heating tally by its name
    tally = sp.get_tally(name='Component-Heating-Tally')

    # Convert the tally results to a pandas DataFrame for easy viewing
    df = tally.get_pandas_dataframe()

    print('--- Component Heating Results ---')
    # Display relevant columns: cell, score, mean (eV/source neutron), and standard deviation
    print(df[['cell', 'score', 'mean', 'std. dev.']])

