import openmc

# Open the statepoint file generated by the simulation
with openmc.StatePoint('statepoint.100.h5') as sp:
    # Retrieve the tally by its name
    tally = sp.get_tally(name='Tritium-Br-Tally')

    # Convert the tally results to a pandas DataFrame for easy viewing
    df = tally.get_pandas_dataframe()

    print('--- Tritium Breeding Ratio (TBR) Results ---')
    print(df[['cell', 'nuclide', 'score', 'mean', 'std. dev.']])
