import openmc
import numpy as np

def extract_heating_and_tbr():
    # Load the statepoint file generated by OpenMC
    # (Update the filename if your batch count changes the output name)
    statepoint_file = "statepoint.100.h5"
    
    try:
        with openmc.StatePoint(statepoint_file) as sp:
            print(f"Successfully loaded {statepoint_file}")
            
            # --- 1. Extract Tritium Breeding Ratio (TBR) ---
            tbr_tally = sp.get_tally(name='TBR')
            tbr_mean = tbr_tally.mean.ravel()[0]
            tbr_std_dev = tbr_tally.std_dev.ravel()[0]
            print(f"\n--- Neutronics Performance ---")
            print(f"Tritium Breeding Ratio (TBR): {tbr_mean:.4f} +/- {tbr_std_dev:.4f}")
            
            # --- 2. Extract Volumetric Heating Mesh ---
            heating_tally = sp.get_tally(name='volumetric_heating')
            
            # Mean heating values in eV/source-neutron per mesh voxel
            heating_data = heating_tally.mean
            
            # Reshape or inspect dimensions (shape is typically [mesh_z, mesh_y, mesh_x, scores])
            print(f"\n--- Thermal Data Extraction ---")
            print(f"Heating mesh data shape: {heating_data.shape}")
            print(f"Peak voxel heating value: {np.max(heating_data):.2e} eV/source-neutron")
            
            # Note: To convert this to W/cm^3, multiply by your total source neutron 
            # emission rate (neutrons/sec) and convert eV to Joules (1.60218e-19 J/eV),
            # then divide by the volume of a single mesh voxel.
            
            return heating_data, tbr_mean

    except FileNotFoundError:
        print(f"Error: Could not find {statepoint_file}. Run 'openmc' first to generate results.")

if __name__ == '__main__':
    extract_heating_and_tbr()

